packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  prisma: true
minimumReleaseAgeExclude:
  - '@types/node@24.13.5'
  - prettier@3.9.7
overrides:
  deepmerge-ts: 8.0.2
  mysql2: 3.24.4
