export interface NotYetImplementedRoute {
  method: string;
  path: string;
}

export const NOT_YET_IMPLEMENTED: readonly NotYetImplementedRoute[] = [
  { method: 'GET', path: '/v1/photographers' },
  { method: 'GET', path: '/v1/photographers/:slug' },
  { method: 'GET', path: '/v1/me/photographer-profile' },
  { method: 'PATCH', path: '/v1/me/photographer-profile' },
  { method: 'GET', path: '/v1/me/photographer-profile/portfolio' },
  { method: 'PATCH', path: '/v1/me/photographer-profile/portfolio/order' },
  { method: 'DELETE', path: '/v1/me/photographer-profile/portfolio/:imageId' },
  { method: 'GET', path: '/v1/photographers/:slug/products' },
  { method: 'GET', path: '/v1/me/products' },
  { method: 'POST', path: '/v1/me/products' },
  { method: 'GET', path: '/v1/me/products/:productId' },
  { method: 'PATCH', path: '/v1/me/products/:productId' },
  { method: 'DELETE', path: '/v1/me/products/:productId' },
  { method: 'POST', path: '/v1/requests' },
  { method: 'GET', path: '/v1/requests/mine' },
  { method: 'GET', path: '/v1/requests/:id' },
  { method: 'POST', path: '/v1/requests/:id/cancel' },
  { method: 'POST', path: '/v1/quotes' },
  { method: 'GET', path: '/v1/quotes/mine' },
  { method: 'GET', path: '/v1/requests/:requestId/quotes' },
  { method: 'POST', path: '/v1/quotes/:id/accept' },
  { method: 'POST', path: '/v1/quotes/:id/decline' },
  { method: 'POST', path: '/v1/quotes/:id/withdraw' },
  { method: 'GET', path: '/v1/bookings' },
  { method: 'GET', path: '/v1/bookings/:id' },
  { method: 'POST', path: '/v1/bookings/:id/delivery' },
  { method: 'POST', path: '/v1/bookings/:id/accept-delivery' },
  { method: 'POST', path: '/v1/bookings/:id/cancel' },
  { method: 'POST', path: '/v1/bookings/:id/payment-intent' },
  { method: 'POST', path: '/v1/uploads' },
  { method: 'POST', path: '/v1/uploads/:id/complete' },
  { method: 'GET', path: '/v1/uploads/:id' },
  { method: 'GET', path: '/v1/uploads/:id/download' },
  { method: 'GET', path: '/v1/conversations' },
  { method: 'GET', path: '/v1/conversations/:id' },
  { method: 'GET', path: '/v1/conversations/:id/messages' },
  { method: 'POST', path: '/v1/conversations/:id/messages' },
  { method: 'POST', path: '/v1/conversations/:id/read' },
  { method: 'POST', path: '/v1/conversations/:id/archive' },
  { method: 'GET', path: '/v1/countries/:code/verification-requirements' },
  { method: 'GET', path: '/v1/me/verification-case' },
  { method: 'POST', path: '/v1/me/verification-case' },
  { method: 'PATCH', path: '/v1/me/verification-case' },
  { method: 'POST', path: '/v1/me/verification-case/documents' },
  { method: 'POST', path: '/v1/me/verification-case/submit' },
  { method: 'GET', path: '/v1/admin/users' },
  { method: 'GET', path: '/v1/admin/users/:id' },
  { method: 'POST', path: '/v1/admin/users/:id/suspend' },
  { method: 'POST', path: '/v1/admin/users/:id/reactivate' },
  { method: 'PUT', path: '/v1/admin/users/:id/roles' },
  { method: 'GET', path: '/v1/admin/verification-cases' },
  { method: 'GET', path: '/v1/admin/verification-cases/:id' },
  { method: 'POST', path: '/v1/admin/verification-cases/:id/approve' },
  { method: 'POST', path: '/v1/admin/verification-cases/:id/reject' },
  { method: 'GET', path: '/v1/admin/provenance-checks' },
  { method: 'GET', path: '/v1/admin/provenance-checks/:id' },
  { method: 'POST', path: '/v1/admin/provenance-checks/:id/approve' },
  { method: 'POST', path: '/v1/admin/provenance-checks/:id/reject' },
  { method: 'GET', path: '/v1/admin/bookings' },
  { method: 'GET', path: '/v1/admin/bookings/:id' },
  { method: 'POST', path: '/v1/admin/bookings/:id/refund' },
  { method: 'POST', path: '/v1/admin/bookings/:id/reverse-transfer' },
  { method: 'GET', path: '/v1/admin/reports' },
  { method: 'POST', path: '/v1/admin/reports/:id/resolve' },
  { method: 'GET', path: '/v1/admin/settings' },
  { method: 'PATCH', path: '/v1/admin/settings' },
  { method: 'GET', path: '/v1/admin/audit-log' },
  { method: 'POST', path: '/v1/me/data-requests' },
  { method: 'GET', path: '/v1/me/data-requests' },
  { method: 'POST', path: '/v1/consents' },
];
