export interface NotYetImplementedRoute {
  method: string;
  path: string;
}

export const NOT_YET_IMPLEMENTED: readonly NotYetImplementedRoute[] = [
  { method: 'GET', path: '/v1/bookings' },
  { method: 'GET', path: '/v1/bookings/:id' },
  { method: 'POST', path: '/v1/bookings/:id/delivery' },
  { method: 'POST', path: '/v1/bookings/:id/accept-delivery' },
  { method: 'POST', path: '/v1/bookings/:id/cancel' },
  { method: 'POST', path: '/v1/bookings/:id/payment-intent' },
  { method: 'POST', path: '/v1/bookings/:id/refund' },
  { method: 'POST', path: '/v1/me/stripe/account-link' },
  { method: 'POST', path: '/v1/stripe/webhook' },
  { method: 'GET', path: '/v1/admin/provenance-checks' },
  { method: 'GET', path: '/v1/admin/provenance-checks/:id' },
  { method: 'POST', path: '/v1/admin/provenance-checks/:id/approve' },
  { method: 'POST', path: '/v1/admin/provenance-checks/:id/reject' },
  { method: 'GET', path: '/v1/admin/bookings' },
  { method: 'GET', path: '/v1/admin/bookings/:id' },
  { method: 'POST', path: '/v1/admin/bookings/:id/refund' },
  { method: 'POST', path: '/v1/admin/bookings/:id/reverse-transfer' },
  { method: 'GET', path: '/v1/me/professional-profile' },
  { method: 'POST', path: '/v1/me/professional-profile' },
  { method: 'PATCH', path: '/v1/me/professional-profile' },
  { method: 'GET', path: '/v1/job-offers' },
  { method: 'GET', path: '/v1/job-offers/:slug' },
  { method: 'GET', path: '/v1/me/job-offers' },
  { method: 'POST', path: '/v1/me/job-offers' },
  { method: 'GET', path: '/v1/me/job-offers/:id' },
  { method: 'PATCH', path: '/v1/me/job-offers/:id' },
  { method: 'DELETE', path: '/v1/me/job-offers/:id' },
  { method: 'POST', path: '/v1/me/job-offers/:id/publish' },
  { method: 'POST', path: '/v1/me/job-offers/:id/close' },
  { method: 'GET', path: '/v1/job-offers/:id/applications' },
  { method: 'POST', path: '/v1/job-offers/:id/applications' },
  { method: 'GET', path: '/v1/me/job-applications' },
  { method: 'POST', path: '/v1/job-applications/:id/status' },
];
